Console.Clear();
Console.SetCursorPosition(0,0);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(0,1);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(8,1);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("          ");
Console.SetCursorPosition(0,2);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(6,2);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("                  ");
Console.SetCursorPosition(0,3);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(6,3);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("      ");
Console.SetCursorPosition(6,3);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("    ");
Console.SetCursorPosition(16,3);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("  ");
Console.SetCursorPosition(12,3);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("    ");
Console.SetCursorPosition(18,3);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("  ");
Console.SetCursorPosition(0,4);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(4,4);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("              ");
Console.SetCursorPosition(6,4);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("  ");
Console.SetCursorPosition(10,4);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("      ");
Console.SetCursorPosition(18,4);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("      ");
Console.SetCursorPosition(0,5);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(4,5);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("  ");
Console.SetCursorPosition(6,5);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("                    ");
Console.SetCursorPosition(8,5);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("    ");
Console.SetCursorPosition(18,5);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("  ");
Console.SetCursorPosition(0,6);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(4,6);
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine("                    ");
Console.SetCursorPosition(8,6);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("        ");
Console.SetCursorPosition(0,7);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(8,7);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("              ");
Console.SetCursorPosition(0,8);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(6,8);
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.WriteLine("            ");
Console.SetCursorPosition(10,8);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("  ");
Console.SetCursorPosition(0,9);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(4,9);
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.WriteLine("                    ");
Console.SetCursorPosition(10,9);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("  ");
Console.SetCursorPosition(16,9);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("  ");
Console.SetCursorPosition(0,10);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(2,10);
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.WriteLine("                        ");
Console.SetCursorPosition(10,10);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("  ");
Console.SetCursorPosition(16,10);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("  ");
Console.SetCursorPosition(0,11);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(2,11);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("                        ");
Console.SetCursorPosition(6,11);
Console.BackgroundColor = ConsoleColor.DarkBlue;
Console.WriteLine("                ");
Console.SetCursorPosition(10,11);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("        ");
Console.SetCursorPosition(0,12);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(2,12);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("                        ");
Console.SetCursorPosition(8,12);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("            ");
Console.SetCursorPosition(10,12);
Console.BackgroundColor = ConsoleColor.Yellow;
Console.WriteLine("  ");
Console.SetCursorPosition(16,12);
Console.BackgroundColor = ConsoleColor.Yellow;
Console.WriteLine("  ");
Console.SetCursorPosition(0,13);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(2,13);
Console.BackgroundColor = ConsoleColor.White;
Console.WriteLine("                        ");
Console.SetCursorPosition(6,13);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("                ");
Console.SetCursorPosition(0,14);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(6,14);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("     ");
Console.SetCursorPosition(16,14);
Console.BackgroundColor = ConsoleColor.Red;
Console.WriteLine("     ");
Console.SetCursorPosition(0,15);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(4,15);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.WriteLine("     ");
Console.SetCursorPosition(16,15);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.WriteLine("     ");
Console.SetCursorPosition(0,16);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.SetCursorPosition(2,16);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.WriteLine("       ");
Console.SetCursorPosition(16,16);
Console.BackgroundColor = ConsoleColor.DarkGray;
Console.WriteLine("       ");
Console.SetCursorPosition(0,17);
Console.BackgroundColor = ConsoleColor.Blue;
Console.WriteLine("                            ");
Console.BackgroundColor = ConsoleColor.Black;